version: '2'
services:
    reacttodo-app:
        image: reacttodo
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://reacttodo-postgresql:5432/reacttodo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    reacttodo-postgresql:
        extends:
            file: postgresql.yml
            service: reacttodo-postgresql
